---
- name: Remove motds
  shell: |
    echo '' > /etc/motd
    echo '' > /etc/issue
    echo '' > /etc/issue.net

- name: Restrict Core Dumps - cleanup kernal params
  lineinfile:
    dest: /etc/sysctl.conf
    line: "fs.suid_dumpable = 0"
  notify:
    - reload sysctl

- name: Disable ipv6 part 1
  lineinfile:
    dest: /etc/sysctl.conf
    line: "net.ipv6.conf.all.disable_ipv6 = 1"
  notify:
    - reload sysctl

- name: Disable ipv6 part 2
  lineinfile:
    dest: /etc/sysctl.conf
    line: "net.ipv6.conf.default.disable_ipv6 = 1"
  notify:
    - reload sysctl

- name: Enable ntp
  service: name=ntp enabled=yes state=started

- name: Disable unscd
  service: name=unscd enabled=no state=stopped    