---
- name: Create admin user
  user:
    name: "{{ ssh_user }}"
    state: present
    groups: "{{ ssh_groups }}"
    shell: /bin/bash
    append: yes
    createhome: yes

- file:
    path: /home/{{ ssh_user }}
    mode: 0700

- name: Deploy ssh public key
  authorized_key: user="{{ ssh_user }}" key="{{ ssh_pub_key }}"

- name: Setup bashrc
  copy:
    src: templates/bashrc
    dest: /home/{{ ssh_user }}/.bashrc
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: 0600

- file:
    path: /home/{{ ssh_user}}/{{ item }}
    state: absent
  with_items:
    - .profile
    - .bash_logout
    - .cloud-locale-test.skip

- file:
    src: /home/{{ ssh_user }}/.bashrc
    dest: /home/{{ ssh_user }}/.profile
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    state: link
    mode: 0600

- file:
    path: /home/{{ ssh_user }}/.hushlogin
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    state: touch
    mode: 0600
