---
- name: Register Droplet
  digital_ocean_droplet:
    backups: "no"
    image: "{{ do_image }}"
    ipv6: "no"
    monitoring: "yes"
    name: "{{ do_droplet_name }}"
    oauth_token: "{{ do_api_token }}"
    private_networking: "no"
    region: "{{ do_region }}"
    size: "{{ do_size }}"
    ssh_keys: "{{ do_ssh_key_fingerprint }}"
    state: present
    unique_name: "yes"
    wait: "yes"
  register: do_droplet

- debug:
    msg: "ID is {{ do_droplet.data.droplet.id }}, IP is {{ do_droplet.data.ip_address }}"

- name: Wait for droplet to finish booting
  pause:
    seconds: 30

- name: Add new droplet to inventory
  add_host:
    name: "{{ do_droplet_name }}"
    groups: dohosts
    ansible_ssh_host: "{{ do_droplet.data.ip_address }}"
    ansible_ssh_user: root
    ansible_ssh_private_key_file: "{{ do_ssh_private_key }}"