---
### Lego
- stat: path=/usr/bin/lego
  register: lego_binary

- stat: path=/tmp/lego
  register: lego_package

- name: Download lego
  unarchive:
    remote_src: true
    src: https://github.com/go-acme/lego/releases/download/v2.6.0/lego_v2.6.0_linux_amd64.tar.gz
    dest: /tmp/
  when:
    - lego_binary.stat.exists == False
    - lego_package.stat.exists == False

- name: Install lego binary
  copy: 
    remote_src: yes 
    src: /tmp/lego
    dest: /usr/bin/lego
    mode: 0755
  when:
    - lego_binary.stat.exists == False

- find:
    paths: /tmp/
    patterns: "*"
  register: files_to_delete

- name: Cleanup /tmp
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"

## minio-client (mc)
- stat: path=/usr/bin/mc
  register: mc_binary

- name: Download minio client
  get_url: 
    url: https://dl.minio.io/client/mc/release/linux-amd64/mc
    dest: /usr/bin/mc
  when:
    - mc_binary.stat.exists == False

- file:
    path: /usr/bin/mc
    mode: 0755

## certigo
- stat: path=/usr/bin/certigo
  register: certigo_binary

- name: Download certigo
  get_url:
    url: https://github.com/square/certigo/releases/download/v1.11.0/certigo-linux-amd64
    dest: /usr/bin/certigo
  when:
    certigo_binary.stat.exists == False

- file:
    path: /usr/bin/certigo
    mode: 0755
