---
- name: update apt cache
  apt: 
    update_cache: true

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install useful/necessary packages
  apt: name={{ item }} state=latest
  with_items:
    - curl
    - dnsutils
    - git
    - htop
    - ipset
    - locate
    - net-tools
    - xz-utils
