- name: Strict SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^#?{{ item.key }}'
    line: '{{ item.key }} {{ item.value }}'
    validate: '/usr/sbin/sshd -t -f %s'
  with_items:
    - { key: 'PermitRootLogin',        value: 'no' }
    - { key: 'PasswordAuthentication', value: 'no' }
    - { key: 'AllowGroups',            value: '{{ ssh_groups }}' }
    - { key: 'MaxAuthTries',           value: "5" }
    - { key: 'LoginGraceTime',         value: "60" }
    - { key: 'MaxSessions',            value: "5" }
    - { key: 'MaxStartups',            value: "10:30:60" }
    - { key: 'Port',                   value: '{{ ssh_port }}' }
    - { key: 'X11Forwarding',          value: 'no' }
  notify: restart sshd